output "db_instance_endpoint" {
  # Use .address instead of .endpoint if you want just the hostname (cleaner for some apps)
  value = aws_db_instance.postgres.address
}

# CHANGE THIS: Point to the SSM Parameter instead of Secrets Manager
output "db_password_ssm_arn" {
  value       = aws_ssm_parameter.db_password.arn
  description = "The ARN of the SSM parameter for the ECS task definition"
}

# The network address (endpoint) of the RDS instance
output "rds_address" {
  value       = aws_db_instance.postgres.address
  description = "The hostname of the RDS database"
}

# The password generated by your random_password resource
output "rds_password" {
  value       = random_password.db_pass.result
  description = "The password for the RDS database admin user"
  sensitive   = true # This prevents the password from printing in plain text in your terminal logs
}